### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/R-Python_Exercise_1_Udit_Chaudhary_Python#1]
Hi Udit, 

Great work on the assignment.
Some relatively minor feedback: I would like to see authorship (first name, last name) on all notebooks. This help collaborators know who to contact with any issues from the code or notebook in general.

I would also prefer that you use the template repositories that I created. Some may contain an autograder, so this would not be present in repositories you create from scratch.

I'm giving you full credit, contingent on you adding authorship by September 15th.
-Greg

**Comment by uditChaudhary242** [comment]
HI Greg, 

Sorry for not adding the authorship. Now I have uploaded the files again with the authorship. 
And I'll keep in mind to use the template repositories in future.
-Udit

**Comment by Gchism94** [comment]
This looks good Udit, great work. 
Next time, please close the issue once you believe you've addressed it. I can always reopen it if I need to. 
-Greg
